# Generated by Django 2.1.5 on 2019-02-13 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('website', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Kort',
            },
            bases=('wagtailcore.page',),
        ),
    ]
